# Site settings
# in the templates available like {{ site.myvariable }}.
title: Bogdan Ostojic portfolio.
email: alukobond93@gmail.com
brand: Bogdan Ostojic
headline: IT undergrad, programming enthusiast.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/bogdanostojic" # the base hostname & protocol for your site
copyright: 2016 Bogdan Ostojic.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 

# Contacts
email: alukobond93@gmail.com
#phone: 
github: https://github.com/bogdanostojic
